<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><meta name="author" content="Zane,pi@0php.net"><title>PHP 异常处理三连 try catch finally · 一只贱熊猫的博客</title><meta name="description" content="0x00 简单应用当执行部分可能抛出异常的代码时，catch 可以捕捉到 try 代码段内抛出的异常（前提是 catch 的参数类型和抛出的异常类型相符），类型不符合的异常会继续向上层抛出。比如以下代码：
直接捕获：
1234567891011function foo()&amp;#123;    thro"><meta name="keywords" content="PHP,Web,Swoole,HTML,CSS"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="renderer" content="webkit"><link rel="short icon" href="/images/favicon.png" type="image/x-icon"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/blog_basic.css"><link rel="stylesheet" href="/css/font-awesome.min.css"><link rel="alternate" type="application/atom+xml" title="ATOM 1.0" href="/atom.xml"></head><body><div class="sidebar animated fadeInDown"><div class="logo-title"><div class="title"><img src="/images/logo@2x.png" style="width:127px;"><h3 title=""><a href="/">一只贱熊猫的博客</a></h3><div class="description"><p>夫夷以近，则游者众；险以远，则至者少。</p></div></div></div><ul class="social-links"><li><a href="http://github.com/zanemmm"><i class="fa fa-github"></i></a></li></ul><div class="footer"><a target="_blank" href="/"><span>Theme by </span></a><a href="https://www.caicai.me"> CaiCai </a><span>&</span><a href="https://github.com/Ben02/hexo-theme-Anatole"> Ben</a><div class="by_farbox"><a href="https://hexo.io/zh-cn/" target="_blank">Proudly published with Hexo&#65281;</a></div></div></div><div class="main"><div class="page-top animated fadeInDown"><div class="nav"><li><a href="/">首页</a></li><li><a href="/about">关于</a></li><li><a href="/archives">归档</a></li><li><a href="/links">友链</a></li></div><div class="information"><div class="back_btn"><li><a class="fa fa-chevron-left" onclick="window.history.go(-1)"> </a></li></div><div class="avatar"><img src="/images/logo.png"></div></div></div><div class="autopagerize_page_element"><div class="content"><div class="post-page"><div class="post animated fadeInDown"><div class="post-title"><h3><a>PHP 异常处理三连 try catch finally</a></h3></div><div class="post-content"><h2 id="0x00-简单应用"><a href="#0x00-简单应用" class="headerlink" title="0x00 简单应用"></a>0x00 简单应用</h2><p>当执行部分可能抛出异常的代码时，<code>catch</code> 可以捕捉到 <code>try</code> 代码段内抛出的异常（前提是 <code>catch</code> 的参数类型和抛出的异常类型相符），类型不符合的异常会继续向上层抛出。比如以下代码：</p>
<p>直接捕获：</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>(<span class="string">'hello world'</span> . PHP_EOL);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    foo();</span><br><span class="line">&#125; <span class="keyword">catch</span> (<span class="keyword">Exception</span> $e) &#123;</span><br><span class="line">    <span class="keyword">echo</span> $e-&gt;getMessage();</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出 hello world</span></span><br></pre></td></tr></table></figure>
<p>抛出至上层捕获：</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException();</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        foo();</span><br><span class="line">    &#125; <span class="keyword">catch</span> (OutOfRangeException $e) &#123;</span><br><span class="line">        <span class="keyword">echo</span> <span class="string">'catch OutOfRangeException'</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125; <span class="keyword">catch</span> (RuntimeException $e) &#123;</span><br><span class="line">    <span class="keyword">echo</span> <span class="string">'catch RuntimeException'</span>;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出 catch RuntimeException</span></span><br></pre></td></tr></table></figure>
<p>可以使用多个连续 <code>catch</code> 捕获不同类型的异常，示例如下：</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">if</span> (random_int(<span class="number">0</span>, <span class="number">1</span>)) &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException();</span><br><span class="line">    &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> OutOfRangeException();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    foo();</span><br><span class="line">&#125; <span class="keyword">catch</span> (OutOfRangeException $e) &#123;</span><br><span class="line">    <span class="keyword">echo</span> <span class="string">'catch OutOfRangeException'</span>;</span><br><span class="line">&#125; <span class="keyword">catch</span> (RuntimeException $e) &#123;</span><br><span class="line">    <span class="keyword">echo</span> <span class="string">'catch RuntimeException'</span>;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 根据随机抛出的异常分别输出</span></span><br><span class="line"><span class="comment">// catch OutOfRangeException</span></span><br><span class="line"><span class="comment">// catch RuntimeException</span></span><br></pre></td></tr></table></figure>
<p><strong>PHP 7.1 新特性</strong>：同一个 <code>catch</code> 可以通过 <code>|</code> 分割异常类型，实现捕获多种异常。示例如下：</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">if</span> (random_int(<span class="number">0</span>, <span class="number">1</span>)) &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException(<span class="string">'I am RuntimeException'</span>);</span><br><span class="line">    &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> OutOfRangeException(<span class="string">'I am OutOfRangeException'</span>);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    foo();</span><br><span class="line">&#125; <span class="keyword">catch</span> (OutOfRangeException|RuntimeException $e) &#123;</span><br><span class="line">    <span class="keyword">echo</span> $e-&gt;getMessage();</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 根据随机抛出的异常分别输出</span></span><br><span class="line"><span class="comment">// I am RuntimeException</span></span><br><span class="line"><span class="comment">// I am OutOfRangeException</span></span><br></pre></td></tr></table></figure>
<h2 id="0x01-返回值的注意事项"><a href="#0x01-返回值的注意事项" class="headerlink" title="0x01 返回值的注意事项"></a>0x01 返回值的注意事项</h2><p>在没有引入 <code>finally</code> 关键字时，在 <code>try...catch</code> 的中返回值是符合直觉的如下例：</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>();</span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (<span class="keyword">Exception</span> $e) &#123;</span><br><span class="line">        <span class="keyword">return</span> <span class="number">2</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">echo</span> foo();</span><br><span class="line"><span class="comment">// 输出 2</span></span><br><span class="line"><span class="comment">// 若只删除抛出异常的代码则输出 1</span></span><br><span class="line"><span class="comment">// 若只删除 catch 中的 return 则无输出</span></span><br></pre></td></tr></table></figure>
<p>但引入 <code>finally</code> 关键字的代码如下:</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>();</span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (<span class="keyword">Exception</span> $e) &#123;</span><br><span class="line">        <span class="keyword">return</span> <span class="number">2</span>;</span><br><span class="line">    &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">        <span class="keyword">return</span> <span class="number">3</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">echo</span> foo();</span><br><span class="line"><span class="comment">// 输出 3</span></span><br></pre></td></tr></table></figure>
<p><code>finally</code> 内的代码是<strong>无论是否捕获到异常都会执行的代码，并且当 <code>finally</code> 中存在 <code>return</code> 返回值时，整个<code>try..catch...finally</code>段的返回值只会是 <code>finally</code> 的返回值。</strong></p>
<p>猜测下例代码输出</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">$a = <span class="number">1</span>;</span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">(&amp;$a)</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        $a = <span class="number">2</span>;</span><br><span class="line">        <span class="keyword">return</span> $a;</span><br><span class="line">    &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">        $a = <span class="number">3</span>;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">echo</span> foo($a);</span><br><span class="line"><span class="keyword">echo</span> $a;</span><br></pre></td></tr></table></figure>
<p>输出结果为 <code>23</code> 这说明了<strong><code>finally</code> 即使在 <code>try</code> 或 <code>catch</code> 中执行了 <code>return</code> 也同样会执行。</strong></p>
<h2 id="0x02-Throwable-接口"><a href="#0x02-Throwable-接口" class="headerlink" title="0x02 Throwable 接口"></a>0x02 Throwable 接口</h2><p><code>Throwable</code> 是 PHP 7 新出的一个预定义接口，<code>Error</code> 和 <code>Exception</code> 类都实现了这个接口，也就是说我们现在有能力通过 <code>catch</code> 捕获到 <code>Error</code>。示例如下：</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">(int $a)</span>: <span class="title">int</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">return</span> $a;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    foo(<span class="string">'string'</span>);</span><br><span class="line">&#125; <span class="keyword">catch</span> (Throwable $e) &#123;</span><br><span class="line">    <span class="keyword">echo</span> get_class($e);</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出 Throwable</span></span><br></pre></td></tr></table></figure>
<p>例子表明了参数类型不符所抛出的 <code>TypeError</code> 错误可以被 <code>catch</code> 捕获。</p>
<h2 id="0x03-全局异常处理函数"><a href="#0x03-全局异常处理函数" class="headerlink" title="0x03 全局异常处理函数"></a>0x03 全局异常处理函数</h2><p>官方文档 <a href="http://php.net/manual/zh/function.set-exception-handler.php" target="_blank" rel="noopener">set_exception_handler</a> 设置一个全局的异常处理函数可以捕获所有没有被 <code>catch</code> 到的异常。使用示例：</p>
<figure class="highlight php"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">set_exception_handler(<span class="function"><span class="keyword">function</span> <span class="params">(Exception $e)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">echo</span> $e-&gt;getMessage();</span><br><span class="line">&#125;);</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">function</span> <span class="title">foo</span><span class="params">()</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> <span class="keyword">Exception</span>(<span class="string">'nobody catch me'</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">foo();</span><br><span class="line"><span class="comment">// 输出 nobody catch me</span></span><br></pre></td></tr></table></figure>
<p>类似的对于错误处理有 <a href="http://php.net/manual/en/function.set-error-handler.php" target="_blank" rel="noopener">set_error_handler</a> 函数。</p>
</div><br><p>转载请注明出处:<a href="https://www.0php.net/posts/PHP-异常处理三连-try-catch-finally.html" target="_blank" title="https://www.0php.net/posts/PHP-异常处理三连-try-catch-finally.html">https://www.0php.net/posts/PHP-异常处理三连-try-catch-finally.html</a></p><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><p>本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>进行许可。</p><div class="post-footer"><div class="meta"><div class="info"><i class="fa fa-sun-o"></i><span class="date">2018-08-11</span><i class="fa fa-comment-o"></i><a href="/posts/PHP-异常处理三连-try-catch-finally.html#comments">评论</a><i class="fa fa-tag"></i><a class="tag" href="/tags/PHP/" title="PHP">PHP </a><a class="tag" href="/tags/异常处理/" title="异常处理">异常处理 </a><a class="tag" href="/tags/tips/" title="tips">tips </a></div></div></div></div><div class="share"><div class="evernote"><a class="fa fa-bookmark" href="javascript:(function(){EN_CLIP_HOST='http://www.evernote.com';try{var%20x=document.createElement('SCRIPT');x.type='text/javascript';x.src=EN_CLIP_HOST+'/public/bookmarkClipper.js?'+(new%20Date().getTime()/100000);document.getElementsByTagName('head')[0].appendChild(x);}catch(e){location.href=EN_CLIP_HOST+'/clip.action?url='+encodeURIComponent(location.href)+'&amp;title='+encodeURIComponent(document.title);}})();" ref="nofollow" target="_blank"></a></div><div class="weibo"><a class="fa fa-weibo" href="javascript:void((function(s,d,e){try{}catch(e){}var f='http://service.weibo.com/share/share.php?',u=d.location.href,p=['url=',e(u),'&amp;title=',e(d.title),'&amp;appkey=2924220432'].join('');function a(){if(!window.open([f,p].join(''),'mb',['toolbar=0,status=0,resizable=1,width=620,height=450,left=',(s.width-620)/2,',top=',(s.height-450)/2].join('')))u.href=[f,p].join('');};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0)}else{a()}})(screen,document,encodeURIComponent));"></a></div><div class="twitter"><a class="fa fa-twitter" href="http://twitter.com/home?status=,https://www.0php.net/posts/PHP-异常处理三连-try-catch-finally.html,一只贱熊猫的博客,PHP 异常处理三连 try catch finally,;"></a></div></div><div class="pagination"><ul class="clearfix"><li class="pre pagbuttons"><a class="btn" role="navigation" href="/posts/PHP-输出缓冲区应用.html" title="PHP 输出缓冲区应用">上一篇</a></li><li class="next pagbuttons"><a class="btn" role="navigation" href="/posts/PHP-框架中间件实现.html" title="PHP 框架中间件实现">下一篇</a></li></ul></div><a id="comments"></a><div id="disqus_thread"></div><script>var disqus_shortname = 'zanemmm';
var disqus_identifier = 'posts/PHP-异常处理三连-try-catch-finally.html';
var disqus_title = 'PHP 异常处理三连 try catch finally';
var disqus_url = 'https://www.0php.net/posts/PHP-异常处理三连-try-catch-finally.html';
(function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();</script><script id="dsq-count-scr" src="//#{theme.disqus}.disqus.com/count.js" async></script></div></div></div></div><script src="/js/jquery.js"></script><script src="/js/jquery-migrate-1.2.1.min.js"></script><script src="/js/jquery.appear.js"></script></body></html>